spring:
  ## druid连接池配置
  #  涉及需要切换数据源时
  #  1.不能使用事务，否则数据源不会切换，使用的还是是第一次加载的数据源 。
  #  　　删除 操作多数据源的方法或者类、接口 上的 注解 @Transactional() 即可。
  #  2.第一次加载的数据源之后，第二次（第三次...）操作其它数据源，如果数据源不存在，使用的还是第一次加载的数据源
  #  3.数据源名称最好不要包含下滑线，下滑线的数据源切换不了
  # 默认数据源
  datasource:
    dynamic:
      primary: master
      strict: false
      hikari:
        min-idle: 10
        idle-timeout: 60000
        max-pool-size: 20
        connection-timeout: 60000
        connection-test-query: SELECT 1
        max-lifetime: 0
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://localhost:3306/instance?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
          username: root
          password: root
          driverClassName: com.mysql.cj.jdbc.Driver
        slave:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://localhost:3306/instance?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
          username: root
          password: root
          driverClassName: com.mysql.cj.jdbc.Driver
        orc:
          hikari:
            min-idle: 10
            idle-timeout: 180000
            max-pool-size: 20
            connection-timeout: 30000
            connection-test-query: SELECT 1 from dual
            max-lifetime: 1800000
          url: jdbc:oracle:thin:@localhost:1521:orcl
          username: scott
          password: 123456
          driverClassName: oracle.jdbc.driver.OracleDriver

